version: '3'

services:
  server:
    build: server
    restart: always
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyACM2:/dev/ttyACM2"
      - "/dev/ttyACM3:/dev/ttyACM3"
